# Copyright The DiGiT Authors
# SPDX-License-Identifier: Apache-2.0

# Standard
from typing import Iterable, List
import time

# Local
from fms_dgt.base.block import get_row_name
from fms_dgt.base.data_objects import DataPoint
from fms_dgt.base.databuilder.base import DataBuilder
from fms_dgt.base.task import TransformationTask
from fms_dgt.base.telemetry import Span


# ===========================================================================
#                       TRANSFORMATION
# ===========================================================================
class TransformationDataBuilder(DataBuilder):
    """This class is designed to have sensible default methods for transformation use cases"""

    def execute_tasks(self):
        """Main entry point for task execution. Default behavior iterates over all tasks and applies the transformation to each task's data."""
        tasks = self._tasks + []

        # Load tasks
        for task in tasks:
            if not isinstance(task, TransformationTask):
                raise TypeError(
                    f"Task {task.name} must inherit from TransformTask class to be used with TransformationDataBuilder"
                )

            task.load_dataloader_state()
            self._register_task_log_handler(task)
            self.logger.info(
                "Task '%s' started.",
                task.name,
                extra={
                    "event": "task_started",
                    "task_name": task.name,
                },
            )

        # Initialize necessary variables
        start_time = time.time()

        # Transform tasks
        for transformed_datapoint in self.call_with_task_list(tasks):
            # save incrementally
            task = next(task for task in tasks if get_row_name(transformed_datapoint) == task.name)
            task.save_intermediate_data(transformed_datapoint)
            task.save_dataloader_state()

            task.machine_data.append(transformed_datapoint)

        # Report performance
        self.logger.info("*" * 99)
        self.logger.info(
            "%s\t\tTotal",
            " " * 40,
        )
        for task in tasks:
            report_str = f"{task.name if len(task.name) <= 37 else task.name[:37]+'...':<40}\t\t{len(task.machine_data):^20}"
            self.logger.info(report_str)

        self.logger.info("*" * 99)

        # Capture counts after transformation, before postprocessing
        counts_before_postproc = {task.name: len(task.machine_data) for task in tasks}

        # Launch postprocessing (timed span, consistent with generation pipeline)
        self.logger.info("Launch postprocessing")
        with Span("dgt.postprocessing", self._span_writer):
            self.execute_postprocessing(tasks)
        self.logger.info("Postprocessing completed")

        self.logger.info(
            "Transformation finished",
            extra={
                "event": "transformation_finished",
                "task_counts": {
                    task.name: {
                        "before": counts_before_postproc[task.name],
                        "after": len(task.machine_data),
                    }
                    for task in tasks
                },
            },
        )

        # Terminate completed tasks
        for task in tasks:
            self.logger.info(
                "Task '%s' finished.",
                task.name,
                extra={
                    "event": "task_finished",
                    "task_name": task.name,
                    "reason": "complete",
                },
            )
            # Do NOT unregister here — see generation execute_tasks() note above.
            task.finish()

        # Report transformation duration
        self.logger.info("Transformation took %.2fs", time.time() - start_time)

    def call_with_task_list(self, tasks: List[TransformationTask]) -> Iterable[DataPoint]:
        """Executes data builder __call__ function for all in-progress tasks.

        Args:
            tasks (List[SdgTask]): List of in-progress tasks

        Returns:
            Iterable[DataPoint]: List of data instances generated by the __call__ function
        """
        # Create pool of data points to transform
        data_pool = [e for task in tasks for e in task.get_batch_examples()]

        # Iterate till all data points are transformed
        while data_pool:
            args = [data_pool]
            kwargs = dict()

            # Trigger transformation
            for output in self(*args, **kwargs):
                yield output

            # Reset data pool with next set of examples to transform
            data_pool = [e for task in tasks for e in task.get_batch_examples()]

    def __call__(
        self,
        data_points: List[DataPoint],
    ) -> List[DataPoint]:
        """Contains the main logic of a data builder. Takes in a list of data objects to transform and returns a list of transformed data objects

        Args:
            data_points (List[DataPoint]): List of data objects to transform

        Returns:
            List[DataPoint]: List of transformed data objects
        """
        raise NotImplementedError(
            f"Missing implementation in {self.__module__}.{self.__class__.__name__}"
        )
